name: Generate Doxygen Documentation

on:
  push:
    branches:
      - main  # Adjust to match your branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Doxygen
        run: sudo apt-get update && sudo apt-get install -y doxygen

      - name: Generate Documentation
        run: |
          doxygen Doxyfile  # Replace "Doxyfile" with your Doxygen configuration file name

      - name: Deploy Documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/html  # Adjust if your Doxygen output directory is different
